[package]
name = "example_nova_hello_serde"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
nova_web = { path = "../../nova_web", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
tokio = "1.32"
