[package]
name = "example_nova_hello_world_path"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
nova_web = { path = "../../nova_web" }
tokio = { version = "1.32", features = ["full"] }
